name: Deploy Website

on:
  push:
    branches:
      - main
  issues:
    types:
      - opened
      - edited
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Install Dependencies (Newtonsoft.Json)
        run: dotnet add package Newtonsoft.Json

      - name: Install Dependencies (HtmlAgilityPack)
        run: dotnet add package HtmlAgilityPack

      - name: Generate Site
        run: dotnet run --project fetch_issues.cs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./posts
