name: Deploy Website

on:
  push:
    branches:
      - main
  issues:
    types:
      - opened
      - edited
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jinja2
      - name: Fetch and Generate Posts
        run: |
          export GITHUB_TOKEN=${{ secrets.KOALA_TOKEN }}
          python fetch_issues.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KOALA_TOKEN }}
          publish_dir: ./posts
