name: Deploy Website

on:
  push:
    branches:
      - main
  issues:
    types:
      - opened
      - edited
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1"
      - name: Install Dependencies
        run: dotnet add package Newtonsoft.Json
      - name: Install Dependencies
        run: dotnet add package HtmlAgilityPack
      - name: Generate Site
        run: dotnet run FetchIssues.cs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./posts
